In [14]:
import numpy as np
import pandas as pd
import ast
import pickle

In [18]:
films_data = pd.read_csv('newfilms.csv')
tmdb_data = pd.read_csv('tmdb_5000_movies.csv')

C:\Users\praga\AppData\Local\Temp\ipykernel_13288\3443094846.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  films_data = pd.read_csv('newfilms.csv')

In [21]:
tmdb_data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [22]:
films_data.head()

,film_id,film_name,year,poster_url,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,anthem-of-a-teenage-prophet,Anthem of a Teenage Prophet,2018,https://a.ltrbxd.com/resized/film-poster/3/8/6...,NaN,NaN,NaN
1,elf-buddys-musical-christmas,Elf: Buddy's Musical Christmas,2014,https://a.ltrbxd.com/resized/film-poster/2/3/8...,NaN,NaN,NaN
2,look-at-us-now-mother,"Look at Us Now, Mother!",2016,https://a.ltrbxd.com/resized/film-poster/3/2/6...,NaN,NaN,NaN
3,fate-grand-order-absolute-demonic-front-babylonia,Fate/Grand Order Absolute Demonic Front: Babyl...,2019,https://a.ltrbxd.com/resized/film-poster/6/7/1...,NaN,NaN,NaN
4,memory-2022,Memory,2022,https://a.ltrbxd.com/resized/film-poster/7/3/4...,NaN,NaN,NaN

In [23]:
merged_data = films_data.merge(tmdb_data, left_on='film_name', right_on='title', how='inner')

In [26]:
merged_data.head()

,film_id,film_name,year,poster_url,Unnamed: 4,Unnamed: 5,Unnamed: 6,budget,genres,homepage,...,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,american-dreamz,American Dreamz,2006,https://a.ltrbxd.com/resized/film-poster/4/7/2...,NaN,NaN,NaN,17000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,...,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-03-04,7314027,107.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Imagine a country where more people vote for a...,American Dreamz,4.9,95
1,when-the-cats-away-1929,When the Cat's Away,1929,https://a.ltrbxd.com/resized/film-poster/1/3/7...,NaN,NaN,NaN,0,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,...,"[{""iso_3166_1"": ""FR"", ""name"": ""France""}]",1996-04-03,0,91.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""}]",Released,No man. No job. No cat.,When the Cat's Away,6.1,16
2,conquest-of-the-planet-of-the-apes,Conquest of the Planet of the Apes,1972,https://a.ltrbxd.com/resized/film-poster/5/0/8...,NaN,NaN,NaN,1700000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 878, ""na...",NaN,...,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1972-06-29,9700000,88.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,All new! The revolt of the apes. The most awes...,Conquest of the Planet of the Apes,6.1,236
3,red-dragon-1965,Red Dragon,1965,https://a.ltrbxd.com/resized/film-poster/1/4/1...,NaN,NaN,NaN,78000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 53, ""name...",NaN,...,"[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",2002-09-29,209196298,124.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Before the Silence.,Red Dragon,6.7,1115
4,the-flintstones-in-viva-rock-vegas,The Flintstones in Viva Rock Vegas,2000,https://a.ltrbxd.com/resized/film-poster/5/1/2...,NaN,NaN,NaN,83000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.vivarockvegas.com/,...,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2000-04-28,59468275,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Get ready to rock!,The Flintstones in Viva Rock Vegas,4.4,134

In [27]:
new_data = merged_data[['film_id', 'film_name', 'poster_url']]

In [31]:
new_data.head()

,film_id,film_name,poster_url
0,american-dreamz,American Dreamz,https://a.ltrbxd.com/resized/film-poster/4/7/2...
1,when-the-cats-away-1929,When the Cat's Away,https://a.ltrbxd.com/resized/film-poster/1/3/7...
2,conquest-of-the-planet-of-the-apes,Conquest of the Planet of the Apes,https://a.ltrbxd.com/resized/film-poster/5/0/8...
3,red-dragon-1965,Red Dragon,https://a.ltrbxd.com/resized/film-poster/1/4/1...
4,the-flintstones-in-viva-rock-vegas,The Flintstones in Viva Rock Vegas,https://a.ltrbxd.com/resized/film-poster/5/1/2...

In [34]:
ratings_data=pd.read_csv('lrat.csv')

In [35]:
ratings_data.head()

  user_name               film_id  rating
0  kurstboy          spider-man-2     4.5
1  kurstboy   tetsuo-the-iron-man     4.0
2  kurstboy  bram-stokers-dracula     4.5
3  kurstboy           poison-2023     4.5
4  kurstboy  the-rat-catcher-2023     3.5

In [36]:
final_data = pd.merge(ratings_data, new_data, on='film_id', how='inner')

In [38]:
final_data.head()

,user_name,film_id,rating,film_name,poster_url
0,kurstboy,spider-man-2,4.5,Spider-Man 2,https://a.ltrbxd.com/resized/sm/upload/pq/mi/k...
1,kurstboy,sideways,4.0,Sideways,https://a.ltrbxd.com/resized/sm/upload/tl/8f/2...
2,kurstboy,legally-blonde,4.5,Legally Blonde,https://a.ltrbxd.com/resized/film-poster/4/7/5...
3,kurstboy,youve-got-mail,3.5,You've Got Mail,https://a.ltrbxd.com/resized/film-poster/4/7/1...
4,kurstboy,poetic-justice,4.0,Poetic Justice,https://a.ltrbxd.com/resized/film-poster/4/7/8...

In [41]:
def get_top_raters(film_name, num_users=5):
  """
  Finds the usernames of the top 'num_users' users who rated a given film the highest.

  Args:
    merged_data: The merged DataFrame containing user_name, film_name, and rating.
    film_name: The name of the film to find top raters for.
    num_users: The number of top-rated users to return.

  Returns:
    A list of usernames of the top 'num_users' raters.
  """

  # Filter the DataFrame for the specified film
  film_ratings = final_data[final_data['film_name'] == film_name]

  # Sort the filtered DataFrame by rating in descending order
  top_raters = film_ratings.sort_values(by='rating', ascending=False)

  # Extract the top 'num_users' usernames
  top_usernames = top_raters['user_name'].head(num_users).tolist()

  return top_usernames

In [42]:
get_top_raters('Batman Begins')

['bartsimpson2389', 'adi0495', 'ccarneiro0707', 'daniellesfilms', 'lvicentini']

In [48]:
import random

In [52]:
def get_highly_rated_movies(top_usernames, min_rating=4.5, num_movies=5):
    """
    Finds and randomizes highly rated movies by the given list of top usernames.

    Args:
        top_usernames: List of usernames whose ratings will be considered.
        min_rating: Minimum rating threshold to consider a movie as highly rated.
        num_movies: Number of top-rated movies to return.

    Returns:
        A list of randomly selected film names rated highly by the given users.
    """
    # Filter the dataset for the top usernames
    user_ratings = final_data[final_data['user_name'].isin(top_usernames)]

    # Filter further for movies with ratings above the specified threshold
    highly_rated = user_ratings[user_ratings['rating'] >= min_rating]

    # Randomize the order of the movies
    randomized_movies = highly_rated.sample(frac=1, random_state=random.randint(1, 1000))

    # Extract the top 'num_movies' film names
    top_film_names = randomized_movies['film_name'].head(num_movies).tolist()

    return top_film_names

In [54]:
get_highly_rated_movies(get_top_raters('Batman Begins'))

['Mulan', 'The Intern', 'Superbad', 'The Shining', 'A Scanner Darkly']

In [55]:
pickle.dump(final_data,open('final_data.pkl','wb'))

In [56]:
final_data

,user_name,film_id,rating,film_name,poster_url
0,kurstboy,spider-man-2,4.5,Spider-Man 2,https://a.ltrbxd.com/resized/sm/upload/pq/mi/k...
1,kurstboy,sideways,4.0,Sideways,https://a.ltrbxd.com/resized/sm/upload/tl/8f/2...
2,kurstboy,legally-blonde,4.5,Legally Blonde,https://a.ltrbxd.com/resized/film-poster/4/7/5...
3,kurstboy,youve-got-mail,3.5,You've Got Mail,https://a.ltrbxd.com/resized/film-poster/4/7/1...
4,kurstboy,poetic-justice,4.0,Poetic Justice,https://a.ltrbxd.com/resized/film-poster/4/7/8...
...,...,...,...,...,...
5967023,beef,in-the-shadow-of-the-moon-2019,3.5,In the Shadow of the Moon,https://a.ltrbxd.com/resized/film-poster/4/5/9...
5967024,beef,black-christmas-2019,3.5,Black Christmas,https://a.ltrbxd.com/resized/film-poster/4/8/0...
5967025,beef,black-christmas,4.0,Black Christmas,https://a.ltrbxd.com/resized/film-poster/4/1/3...
5967026,beef,the-santa-clause,3.0,The Santa Clause,https://a.ltrbxd.com/resized/film-poster/4/5/3...
5967027,beef,pacific-rim,3.5,Pacific Rim,https://a.ltrbxd.com/resized/film-poster/5/2/5...